name: mineunit
on: [push, pull_request]

jobs:
  mineunit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - id: mineunit
      uses: mt-mods/mineunit-actions@master
      with:
        badge-name: standard
        badge-label: Standard
