name: mineunit-lua51
on: [push, pull_request]

jobs:
  mineunit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - id: mineunit
      uses: mt-mods/mineunit-actions@lua-version
      with:
        lua-version: lua51
        badge-name: standard-lua51
        badge-label: Standard Lua 5.1

    - uses: RubbaBoy/BYOB@v1.3.0
      if: success()
      with:
        NAME: "${{ steps.mineunit.outputs.badge-name }}"
        LABEL: "${{ steps.mineunit.outputs.badge-label }}"
        STATUS: "${{ steps.mineunit.outputs.badge-status }}"
        COLOR: "${{ steps.mineunit.outputs.badge-color }}"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - uses: KeisukeYamashita/create-comment@v1
      if: success() && github.event_name == 'pull_request'
      with:
        check-only-first-line: true
        comment: |
          <details><summary><i>Click for detailed source code test coverage report ${{ steps.mineunit.outputs.badge-label }}</i></summary>
          
          ### Test coverage report ${{ steps.mineunit.outputs.coverage-total }} in ${{ steps.mineunit.outputs.coverage-files }} files:
          ```
          File                                      Hits Missed Coverage
          --------------------------------------------------------------
          ${{ steps.mineunit.outputs.mineunit-report }}
          ```
          
          ### Raw test runner output for geeks:
          ```
          ${{ steps.mineunit.outputs.mineunit-stdout }}
          ```
          </details>

    - uses: KeisukeYamashita/create-comment@v1
      if: failure() && github.event_name == 'pull_request'
      with:
        check-only-first-line: true
        comment: |
          <details><summary><i>Mineunit ${{ steps.mineunit.outputs.badge-label }} runner failed, click for details</i></summary>
          
          ### Mineunit log:
          ```
          ${{ steps.mineunit.outputs.mineunit-stdout }}
          ```
          </details>
