name: mineunit-runner
on: [push, pull_request]

jobs:
  mineunit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - id: mineunit
      uses: mt-mods/mineunit-actions@docker
      with:
        badge-name: standard
        badge-label: Standard
