name: mineunit-action-basic
on: [push, pull_request]

jobs:
  mineunit-action-basic:
    runs-on: ubuntu-latest
    container:
      image: docker://mineunit/mineunit:latest
      options: -u root
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/action-basic
      with:
        badge-name: basic
        badge-label: Basic
