name: mineunit-action-docker
on: [push, pull_request]

jobs:
  mineunit-action-docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/action-docker
      with:
        badge-name: docker-local
        badge-label: Docker local
