name: mineunit-docker
on: [push, pull_request]

jobs:
  mineunit-docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - id: mineunit
      uses: S-S-X/mineunit-docker@master
      with:
        badge-name: docker
        badge-label: Docker
        mineunit-args: --engine-version 5.7.0

    - uses: RubbaBoy/BYOB@v1.3.0
      if: success()
      with:
        NAME: "${{ steps.mineunit.outputs.badge-name }}"
        LABEL: "${{ steps.mineunit.outputs.badge-label }}"
        STATUS: "${{ steps.mineunit.outputs.badge-status }}"
        COLOR: "${{ steps.mineunit.outputs.badge-color }}"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - uses: KeisukeYamashita/create-comment@v1
      if: success()
      with:
        check-only-first-line: true
        comment: |
          <details><summary><i>Click for detailed source code test coverage report</i></summary>
          
          ### Test coverage report ${{ steps.mineunit.outputs.coverage-total }} in ${{ steps.mineunit.outputs.coverage-files }} files:
          ```
          File                                      Hits Missed Coverage
          --------------------------------------------------------------
          ${{ steps.mineunit.outputs.mineunit-report }}
          ```
          
          ### Raw test runner output for geeks:
          ```
          ${{ steps.mineunit.outputs.mineunit-stdout }}
          ```
          </details>

    - uses: KeisukeYamashita/create-comment@v1
      if: failure()
      with:
        check-only-first-line: true
        comment: |
          <details><summary><i>Mineunit runner failed, click for details</i></summary>
          
          ### Mineunit log:
          ```
          ${{ steps.mineunit.outputs.mineunit-stdout }}
          ```
          </details>
