name: luacheck
on: [push, pull_request]

jobs:
  mineunit:
    runs-on: ubuntu-latest
    container:
      image: docker://ssxx/mineunit:latest
      options: -u root
    steps:
    - uses: actions/checkout@v2
    - run: mineunit -c
    - run: mineunit -r
    - run: echo "::set-output name=total::$(tail -n 2 luacov.report.out | grep ^Total | grep -o '[0-9.]\+%$')"
